FROM node:22-alpine
WORKDIR /app

COPY turbo.json ./
COPY package.json ./
COPY package-lock.json ./
COPY apps/frontend/package.json ./apps/frontend/package.json

RUN npm i 

COPY . .

RUN npm i 

EXPOSE 5173

CMD ["npm", "run", "dev"]