FROM node:22-alpine

RUN apk add --no-cache dumb-init

ENV NODE_OPTIONS="--dns-result-order=ipv4first"
WORKDIR /app

COPY turbo.json ./
COPY package.json ./
COPY package-lock.json ./
COPY apps/backend/package.json ./apps/backend/package.json

RUN npm i 

COPY . .

RUN npm i 

EXPOSE 3000
EXPOSE 51212

CMD ["npx", "turbo", "run", "dev", "--filter=backend"]