FROM node:22-alpine
WORKDIR /app

COPY turbo.json ./
COPY package.json ./
COPY package-lock.json ./
COPY apps/backend/package.json ./apps/backend/package.json

RUN npm i 

COPY . .

RUN npm i 

EXPOSE 3000

CMD ["npx", "turbo", "run", "dev", "--filter=backend"]