import "dotenv/config";
export const PORT = process.env.PORT! || 3000;
export const NODE_ENV = process.env.NODE_ENV!;
export const JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET!;
export const SALT_ROUNDS = process.env.SALT_ROUNDS!;
export const O_AUTH_CLIENT_ID = process.env.O_AUTH_CLIENT_ID!;
export const O_AUTH_CLIENT_SECRET = process.env.O_AUTH_CLIENT_SECRET!;
export const REDIRECT_URI = process.env.REDIRECT_URI!;
export const BREVO_API_KEY = process.env.BREVO_API_KEY!;
export const REDIS_URL = process.env.REDIS_URL!;
export const FRONTEND_URL = process.env.FRONTEND_URL!;
export const BACKEND_URL = process.env.BACKEND_URL!;
export const PIN_CODE_API_KEY = process.env.PIN_CODE_API_KEY!;
export const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET!;
export const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY!;
export const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME!;
